[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["bob"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.coverage.html]
directory = "build/cov-html/"


[tool.pytest.ini_options]
addopts = "--cov -vv"
minversion = 6.0
required_plugins = "pytest-cov>=3.0.0"
testpaths = [
    "tests",
]

[tool.black]
line-length = 88
target-version = ['py38', 'py39']

[tool.pydocstyle]
convention = "google"

[tool.mypy]
mypy_path = "./src/bob/;./tests/"
show_error_codes = true
