name: Linters

on: [push, pull_request, workflow_dispatch]

jobs:
  code-check:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tox]

      - name: "Run code checks"
        run: tox -e linters

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tox]

      - name: "Run type checks"
        run: tox -e mypy
