name: Linters

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install package
        run: pip install -e .[tox]

      - name: "Run linters"
        run: tox -e linters
