name: UnitTesting

on: [push, pull_request, workflow_dispatch]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install package
        run: pip install -e .[tox]

      - name: "Execute unit-tests"
        run: tox -e py310

      - name: Upload coverage data to coveralls.io
        run: |
          python -m pip install coverage[toml] coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
